### ISSUE TITLE
[#0002] Setup back

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-back#1]

**Comment by ThHenrique** [comment]
# Documentação

## Descrição

1. Iniciar CRUD de usuários
2. Configuração de autenticação e autorização de usuários
3. Configuração do SWAGGER
4. Configuração template Pull Request
5. Configuração docker-compose
6. Configuração README

## Tecnologias

NestJS, Prisma, PostgresSQL, Insomnia e Docker
