### ISSUE TITLE
[#0037] Refatoração: aplicar caixa alta no texto de sentimento

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-back#19]
Atualmente as palavras sobre os sentimentos estão sendo escritas como **"Positivo"**, temos alterar para que sejam escritas como **"POSITIVO"**.

**Comment by drisabelles** [comment]
@GabrielCamargoL 

- [x] Aprovado pelo P.O

**Comment by ThHenrique** [comment]
Documentação: #27
