### ISSUE TITLE
[#0041] Análise Estática de Código Fonte com SonarQube II

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-back#21]

**Comment by ThHenrique** [comment]
@drisabelles Quais os requisitos para essa task nessa sprint ?

**Comment by drisabelles** [comment]
@ThHenrique Nesse caso, a análise estática do código continuaria sendo a análise do que aparece no sonar cloud, atualização da tabela no readme da sprint 2 e as estratégias. No entanto, precisamos dos testes unitários para o Coverage necessário para o Quality Gate assim como haviamos conversado.
