### ISSUE TITLE
[#0403] Query para o ranking de temas

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-back#22]
## Descrição da atividade

- Desenvolver busca na base de dados dos "Top 5 temas mais discutidos".

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
Documentação: #28
