### ISSUE TITLE
[#0503] Query evolução de temas

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-back#23]
## Descrição da atividade

- Desenvolver busca na base de dados sobre a evolução de um tema escolhido.

## Informações para execução da atividade
- Ordenar por created_at ASC
- Medir a satisfação com a média de estrelas (por enquanto, devido ao algoritmo utilizado no NLP)
- ~[groupBy por mes](https://stackoverflow.com/questions/14565788/how-to-group-by-month-from-date-field-using-sql)~

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
Documentação: #29
