### ISSUE TITLE
[#0043] Corrigir filtro de datas

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-back#24]
## Descrição da atividade

- Corrigir filtro de busca por parte de datas

## Informações para execução da atividade
- Inverter a regra do "between do mongodb  gte e lte" (dados depois do dateStart e antes do DateDone)
![Image](https://github.com/The-Bugger-Ducks/mood-hound-back/assets/55204419/83238f7a-43ed-44d1-b47c-d206474118a0)

exemplo:
```typescript
where = {
    ...where,
    createdAt: { gte: filters.dateStart, lte: filters.dateDone },
};
```

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)

## DoD

- [x] Code review
- [x] Testado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
Documentação: #27
