### ISSUE TITLE
[#0405] Avaliações por Estado

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-back#25]
## Descrição da atividade

- retorno para a dashboard sobre quantidade de avaliações por estado brasileiro, conforme o [protótipo](https://whimsical.com/mood-hound-Jatkhh9Ypy6uHj3DuqoMXE@2Ux7TurymMWFyADhobDD).

## Informações para execução da atividade
- Separar Avaliações com groupby por estado e count em cada grupo 

- O retorno deve ser do formato em que o front possa interagir (conversar com a giovana em caso de dúvidas)
exemplo simples para visualização: 
```json
{ 
    "BR-SP": 30000,
    "BR-RJ": 1000,
    "BR-PE": 500,
    "BR-AM": 100
} 
```

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
@GabrielCamargo @drisabelles essa task está pronta ou devemos aguardar ainda ?

**Comment by ThHenrique** [comment]
Pode ser iniciado, @GabrielCamargoL respondeu

**Comment by ThHenrique** [comment]
Documentação: #30
