### ISSUE TITLE
[#0901] CRUD de usuários

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-back#3]
## Descrição da atividade

Criar rotas para cadastro, mudança de role e delete de usuários simples.

## Informações necessárias para execução da atividade.

- Dados do usuário: Nome, e-mail, senha e nível de privilégio (por padrão será simples e poderá ser atualizado posteriormente por um gestor). Todas as informações são obrigatórias.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by drisabelles** [comment]
@GabrielCamargoL @JoaoM-py pelo o que vi (se eu estiver correta), Thiagão está requisitando review de ustedes em https://github.com/The-Bugger-Ducks/mood-hound-back/pull/5

**Comment by ThHenrique** [comment]
# Documentação

## Descrição

Nessa PR foi desenvolvido todas funcionalidades relacionadas a usuário, sem levar em consideração a autorização para realizar as operações, por exemplo, usuário VIEWER editar o privilégio de um usuário ADMIN, isso será conteplado em uma task futura.

Novos métodos
1.  Busca por usuários com filtro (name, email e role)
2.  Visualizar minhas informações
3.  Atualizar minhas informações
4.  Criar usuário
5.  Gerenciar privilégio de usuário
6.  Deletar usuário

Todos esses métodos foram implementados baseando-se nos requisitos dessa task alinhado ao protótipo desenvolvido.

## Tecnologias

NestJS, Prisma, PostgresSQL, Insomnia e Docker

## Outras informações

As novas rotas são estão disponíveis e podem ser testadas no [swagger](http://localhost:3000/api)
