### ISSUE TITLE
[#0417] Gráfico pizza/donut - faixa etária

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-back#45]

**Comment by ThHenrique** [comment]
@GabrielCamargoL quais serão as faixas etárias ?

ex: 18 - 24
24 - 35
35 - 48
....

**Comment by GabrielCamargoL** [comment]
@ThHenrique conforme conversamos

Crianças e Adolescentes:
0-17 anos

Adultos Jovens:
18-24 anos

Adultos de Meia-Idade:
25-34 anos
35-44 anos

Adultos Mais Velhos:
45-59

Idosos:
60 anos ou mais

**Comment by ThHenrique** [comment]
# Documentação

## Descrição

Em comum acordo com o Frontend, o retorno para faixa etaria e genero ficou da seguinte maneira:

```json

["commentsPerAgeGroup": {
    "labels": [
			"0 à 17 anos",
			"18 à 24 anos",
			"25 à 34 anos",
			"35 à 44 anos",
			"55 à 59 anos",
			"+60 anos"
    ],
    "values": [
			1,
			27,
			1059,
			1853,
			1823,
			1237
	]
}]

```
